---
- hosts: ubuntu-bootstrap-root
  become: true
  roles:
    - role: ansible-stuff.ssh
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=stable'
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'origin=Ubuntu,archive=${distro_codename}-updates'
      unattended_remove_unused_dependencies: true
      unattended_automatic_reboot: true
      unattended_ignore_apps_require_restart: true
    - role: kamaln7.swapfile
      swapfile_size: 4G

      # https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04#tweak-your-swap-settings
      # "For a VPS system, we'd probably want to move it closer to 0."
      swapfile_swappiness: 10
      swapfile_vfs_cache_pressure: 50

- hosts: ubuntu-bootstrap-root
  become: true
  vars:
    ssh_key_public_path: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa.pub' }}"
    ssh_key_public: "{{ lookup('file', ssh_key_public_path) }}"
  tasks:
    - apt: name=zsh state=present
    - group:
        name="{{ ubuntu_bootstrap_user_name }}"
    - user:
        name="{{ ubuntu_bootstrap_user_name }}"
        password="{{ ubuntu_bootstrap_user_password }}"
        shell=/bin/zsh
        groups="{{ ubuntu_bootstrap_user_name }},sudo"
    - file:
        path: "/home/{{ ubuntu_bootstrap_user_name }}/.ssh"
        state: directory
        mode: 0700
        owner: "{{ ubuntu_bootstrap_user_name }}"
        group: "{{ ubuntu_bootstrap_user_name }}"
      when: not ubuntu_bootstrap_do_not_copy_key
    # http://stackoverflow.com/a/34929776/2288008
    - copy:
        content: ""
        dest: "/home/{{ ubuntu_bootstrap_user_name }}/.ssh/authorized_keys"
        force: no
        owner: "{{ ubuntu_bootstrap_user_name }}"
        group: "{{ ubuntu_bootstrap_user_name }}"
        mode: 0600
      when: not ubuntu_bootstrap_do_not_copy_key
    - lineinfile:
        path: "/home/{{ ubuntu_bootstrap_user_name }}/.ssh/authorized_keys"
        line: "{{ ssh_key_public }}"
      when: not ubuntu_bootstrap_do_not_copy_key
